/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppEstadisticasRouteImport } from './routes/_app.estadisticas'
import { Route as AppControlRouteImport } from './routes/_app.control'
import { Route as AppBusquedaRouteImport } from './routes/_app.busqueda'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEstadisticasRoute = AppEstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => AppRoute,
} as any)
const AppControlRoute = AppControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AppRoute,
} as any)
const AppBusquedaRoute = AppBusquedaRouteImport.update({
  id: '/busqueda',
  path: '/busqueda',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/busqueda': typeof AppBusquedaRoute
  '/estadisticas': typeof AppEstadisticasRoute
  '/control': typeof AppControlRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/busqueda': typeof AppBusquedaRoute
  '/estadisticas': typeof AppEstadisticasRoute
  '/control': typeof AppControlRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/busqueda': typeof AppBusquedaRoute
  '/_app/estadisticas': typeof AppEstadisticasRoute
  '/_app/control': typeof AppControlRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/busqueda' | '/estadisticas' | '/control'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/busqueda' | '/estadisticas' | '/control' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/busqueda'
    | '/_app/estadisticas'
    | '/_app/control'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estadisticas': {
      id: '/_app/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof AppEstadisticasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/control': {
      id: '/_app/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof AppControlRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/busqueda': {
      id: '/_app/busqueda'
      path: '/busqueda'
      fullPath: '/busqueda'
      preLoaderRoute: typeof AppBusquedaRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBusquedaRoute: typeof AppBusquedaRoute
  AppEstadisticasRoute: typeof AppEstadisticasRoute
  AppControlRoute: typeof AppControlRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBusquedaRoute: AppBusquedaRoute,
  AppEstadisticasRoute: AppEstadisticasRoute,
  AppControlRoute: AppControlRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
